# Generated by Django 4.1.3 on 2022-11-15 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('content', models.TextField()),
                ('directed_by', models.CharField(max_length=150)),
                ('starring', models.CharField(max_length=150)),
                ('release_date', models.CharField(max_length=150)),
                ('running_time', models.CharField(max_length=150)),
                ('photo', models.ImageField(blank=True, upload_to='')),
                ('is_published', models.BooleanField(default=True)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
