# Generated by Django 4.1.3 on 2022-11-15 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News',
            new_name='Films',
        ),
    ]
