# Generated by Django 4.1.3 on 2022-11-15 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_rename_news_films'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='films',
            options={'ordering': ['id'], 'verbose_name': 'Фильм', 'verbose_name_plural': 'Фильмы'},
        ),
        migrations.AlterField(
            model_name='films',
            name='age',
            field=models.IntegerField(verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='films',
            name='content',
            field=models.TextField(verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='films',
            name='directed_by',
            field=models.CharField(max_length=150, verbose_name='Режиссер'),
        ),
        migrations.AlterField(
            model_name='films',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='films',
            name='photo',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='films',
            name='release_date',
            field=models.CharField(blank=True, max_length=150, verbose_name='Дата выхода'),
        ),
        migrations.AlterField(
            model_name='films',
            name='running_time',
            field=models.CharField(max_length=150, verbose_name='Продолжительность'),
        ),
        migrations.AlterField(
            model_name='films',
            name='starring',
            field=models.CharField(blank=True, max_length=150, verbose_name='В главной роли'),
        ),
        migrations.AlterField(
            model_name='films',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Наименование'),
        ),
    ]
