# Generated by Django 4.1.3 on 2022-11-15 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0004_category_films_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='films',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='films.category', verbose_name='Категория'),
        ),
    ]
