# Generated by Django 4.1.3 on 2022-12-01 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0006_alter_films_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='films',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='films.category', verbose_name='Категория'),
            preserve_default=False,
        ),
    ]
