# Generated by Django 4.1.3 on 2022-12-06 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0007_alter_films_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='films',
            name='date_end_view',
            field=models.DateField(default='2022-03-01', verbose_name='Конец показа'),
        ),
        migrations.AddField(
            model_name='films',
            name='date_start_view',
            field=models.DateField(default='2022-01-01', verbose_name='Начало показа'),
        ),
    ]
