# Generated by Django 4.1.3 on 2022-12-09 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0009_alter_films_date_end_view_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='films',
            name='date_end_view',
            field=models.DateField(default='2022-03-01', verbose_name='Конец показа'),
        ),
        migrations.AlterField(
            model_name='films',
            name='date_start_view',
            field=models.DateField(default='2022-01-01', verbose_name='Начало показа'),
        ),
    ]
